### ISSUE TITLE
Allow us to disable detection switch to ELIM_BRACKET

### ISSUE THREAD

**Issue by Droideka1** [MayorMonty/tm-obs-switcher#10]
I personally don't like this feature how it disables Saved Score & rankings automation whenever TM OBS Switcher detects Elimination Bracket slide. We should be able to disable this. 

Loving this app! <3

**Comment by MayorMonty** [comment]
This feature is designed to release control of display automation during the eliminations period, which often has a much more choreographed layout. For example, many events will choose to show the score of the most recently played match before advancing in eliminations. 

Stopping that release would be a simple code change, but I am concerned about the increasing number of options present in the app. An upcoming release adds ATEM support to the switcher, dramatically increasing the configuration options.

I will put this issue on hold until we have a good solution to address all of the options, probably a configuration file that can be read and saved.

**Comment by MayorMonty** [comment]
The new TM API does not support Audience Control interactions, so closed for now
