### ISSUE TITLE
Add Streaming and state columns to CSV output file. 

### ISSUE THREAD

**Issue by paulsp** [MayorMonty/tm-obs-switcher#28]
**Is your feature request related to a problem? Please describe.**
Issue #25 is related to how timestamps for recording and steaming are displayed. In cases where recording, as managed by OBS, and streaming occurs, the timestamps are from the recording and no streaming timestamp are output.

**Describe the solution you'd like**
Record match start timestamps and state, active or paused, for both recording and streaming in the CSV timestamp file.  This would add three columns and rename one column.  As a results the following columns would be output:
- Date from the tm-switcher computer
- Recording Timecode
- Recording State
- Streaming Timecode
- Streaming State
- Match Name
- Teams (could be split into four columns, one per team)

**Describe alternatives you've considered**
Issue #25 partially addresses the issue by adding state to the timestamp value, but only one timestamp is present

**Additional context**
Both this issue and #25 relate to OBS.  ATEM may have similar functionality that is not currently supported by tm-switcher that may need to be added.

**Comment by brenapp** [comment]
Complete in 8eebab2
