### ISSUE TITLE
App Crashed When I Enabled Timestamp

### ISSUE THREAD

**Issue by Droideka1** [MayorMonty/tm-obs-switcher#7]
I entered the info correctly, I typed Y and the app crashes.

**Comment by MayorMonty** [comment]
What Operating System are you using? Can you get the text of the error printed before crashing?

**Comment by Droideka1** [comment]
Windows 11 & there is not error text... 
Sorry for late response.

**Comment by MayorMonty** [comment]
Fixed by 09eea3ea3e539cec9f9e7cbb52e0d380abb347c1
