### ISSUE TITLE
Request for OBS Websockets 5.0 support

### ISSUE THREAD

**Issue by paulsp** [MayorMonty/tm-obs-switcher#8]
The upcoming OSB 28 includes OBS Websockets 5.x.  A OBS Web Sockets 5.0 plugin is available for OBS 27.
This is request to support Websockets 5.0, as the version supported by tm-obs-switcher does not work with version 5.0.

**Comment by MayorMonty** [comment]
Thanks for bringing this to my attention! I will be sure to adapt the module to support the newest protocol built into OBS 28.

**Comment by MayorMonty** [comment]
Fixed by 4d9746676930967b2c73af9941df9fdc837d0fce
